### ISSUE TITLE
Проверить ДЗ №6 - Read Later

### ISSUE THREAD

**Issue by lerucom** [lerucom/js-homework6#1]
@coursar
Развертывание GitHub Pages https://lerucom.github.io/js-homework6/

Реализованные условия:
* Все данные (кроме результатов поиска) хранятся в LocalStorage
* Вкладка "Прочитать" содержит список ссылок (название, теги и ссылка), которые необходимо прочитать
* Форма не добавляет ссылку, которая уже есть в списке "Прочитать" или в списке "Прочитано"
* Теги разделяются символом #
* При нажатии на checkbox прочитано - элемент отправляется на вкладку "Прочитано"
* Вкладка "Прочитано" содержит список ссылок (название, теги и ссылка), которые уже прочитаны
* При нажатии на checkbox прочитано - элемент отправляется обратно на вкладку "Прочитать"
* Вкладка "Поиск" осуществляет поиск по названию и тегу.
* Ссылки открываются в новой вкладке
* Валидация форм

**Comment by coursar** [comment]
Всё хорошо, хотелось бы, чтобы при клике на тег открывалась страница поиска с заполненым этим тегом.

И я бы рекомендовал теги искать по #. Хотя то, как реализовано сейчас - тоже хорошо.
